### ISSUE TITLE
Exception in server tick loop Crash

### ISSUE THREAD

**Issue by Sabert25** [Cursee-Development-OLD/Danger-Close#4]
Happens over and over after some time ingame. Removing this mod fixes it.
Here is my Crashlog:
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-10-16 19:42:37
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 513
	at knot//it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$1.forEach(Int2ObjectLinkedOpenHashMap.java:1718)
	at knot//com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:110)
	at knot//fabric.com.cursee.danger_close.DangerCloseFabric.lambda$onInitialize$1(DangerCloseFabric.java:26)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:833)
	at knot//fabric.com.cursee.danger_close.DangerCloseFabric.lambda$onInitialize$2(DangerCloseFabric.java:22)
	at knot//net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:34)
	at knot//net.minecraft.server.MinecraftServer.handler$dbk000$fabric-lifecycle-events-v1$onStartTick(MinecraftServer.java:5658)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.4, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 9888071680 bytes (9430 MiB) / 17179869184 bytes (16384 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7800X3D 8-Core Processor           
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.12011.1036
	Graphics card #1 name: AMD Radeon RX 7900 XTX
	Graphics card #1 vendor: Advanced Micro Devices, Inc.
	Graphics card #1 VRAM (MiB): 24560.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.12011.1036
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 45412.61
	Virtual memory used (MiB): 40017.30
	Swap memory total (MiB): 13450.62
	Swap memory used (MiB): 136.15
	Space in storage for jna.tmpdir (MiB): available: 1506962.25, total: 1906828.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 1506962.25, total: 1906828.00
	Space in storage for io.netty.native.workdir (MiB): available: 1506962.25, total: 1906828.00
	Space in storage for java.io.tmpdir (MiB): available: 1506962.25, total: 1906828.00
	Space in storage for workdir (MiB): available: 1506962.25, total: 1906828.00
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+ZGenerational -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancednetherite: Advanced Netherite 2.1.6-1.21.1
		advancementplaques: Advancement Plaques 1.6.6
		ambientsounds: AmbientSounds 6.1.2
		amendments: Amendments 1.21-1.2.17
		amplified_nether: Amplified Nether 1.2.5
		animal_feeding_trough: Animal Feeding Trough 1.1.2+1.21.1
		appleskin: AppleSkin 3.0.5+mc1.21
		balm-fabric: Balm 21.0.20
			kuma_api: KumaAPI 21.0.5-SNAPSHOT
		bclib: BCLib 21.0.13
		beb: Beautiful Enchanted Books 1.0.0
		betteradvancements: Better Advancements 0.4.2.19
		bettercombat: Better Combat 2.0.3+1.21.1
		betterend: Better End 21.0.11
		betternether: Better Nether 21.0.11
		betternetherdelight: BetterNether Delight 1.0.0-1.21.x
		betterstats: Better Statistics Screen 3.13.2+fabric-1.21
		betterthanmending: BetterThanMending 2.2.0
		betterthirdperson: Better Third Person 1.9.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.10.2-1.21.1
			multipart_entities: MultipartEntities 1.7-1.21
		c2me: Concurrent Chunk Management Engine 0.3.0+alpha.0.222+1.21.1
			c2me-base: Concurrent Chunk Management Engine (Base) 0.3.0+alpha.0.222+1.21.1
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.3.0+alpha.0.222+1.21.1
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.3.0+alpha.0.222+1.21.1
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.3.0+alpha.0.222+1.21.1
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.3.0+alpha.0.222+1.21.1
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.3.0+alpha.0.222+1.21.1
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.3.0+alpha.0.222+1.21.1
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.3.0+alpha.0.222+1.21.1
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.3.0+alpha.0.222+1.21.1
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.3.0+alpha.0.222+1.21.1
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.3.0+alpha.0.222+1.21.1
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.3.0+alpha.0.222+1.21.1
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.3.0+alpha.0.222+1.21.1
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.3.0+alpha.0.222+1.21.1
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.3.0+alpha.0.222+1.21.1
			c2me-rewrites-chunk-system: Concurrent Chunk Management Engine (Rewrites/Chunk System) 0.3.0+alpha.0.222+1.21.1
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.3.0+alpha.0.222+1.21.1
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.3.0+alpha.0.222+1.21.1
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.3.0+alpha.0.222+1.21.1
			com_ibm_async_asyncutil: asyncutil 0.1.0
			io_reactivex_rxjava3_rxjava: rxjava 3.1.8
			mixinsquared: MixinSquared 0.2.0-beta.6
			net_objecthunter_exp4j: exp4j 0.4.8
			org_jctools_jctools-core: jctools-core 4.0.5
			org_reactivestreams_reactive-streams: reactive-streams 1.0.4
		cameraoverhaul: Camera Overhaul 1.4.1-fabric-universal
		camerautils: Camera Utils 1.21.1-1.0.16
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c6a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a76a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
		cardinal-components: Cardinal Components API 6.1.1
			cardinal-components-base: Cardinal Components API (base) 6.1.1
			cardinal-components-block: Cardinal Components API (blocks) 6.1.1
			cardinal-components-chunk: Cardinal Components API (chunks) 6.1.1
			cardinal-components-entity: Cardinal Components API (entities) 6.1.1
			cardinal-components-item: Cardinal Components API (items) 6.1.1
			cardinal-components-level: Cardinal Components API (world saves) 6.1.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.1.1
			cardinal-components-world: Cardinal Components API (worlds) 6.1.1
		cherishedworlds: Cherished Worlds 10.0.2+1.21.1
		cicada: CICADA 0.8.3+1.21-and-above
		citresewn: CIT Resewn 1.2.1+1.21
			citresewn-defaults: CIT Resewn: Defaults 1.2.1+1.21
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		cobweb: Cobweb 1.1.3
		collective: Collective 7.84
		comforts: Comforts 9.0.2+1.21.1
			spectrelib: SpectreLib 0.17.2+1.21
		connectiblechains: Connectible Chains 2.4.2+1.21.1
		continuity: Continuity 3.0.0-beta.5+1.21
		creativecore: CreativeCore 2.12.16
			net_neoforged_bus: bus 7.2.0
		cristellib: Cristel Lib 1.2.8
			blue_endless_jankson: jankson 1.2.3
		danger_close: Danger Close 3.1.1
		diagonalfences: Diagonal Fences 21.1.0
			diagonalblocks: Diagonal Blocks 21.1.0
		diagonalwalls: Diagonal Walls 21.1.0
		diagonalwindows: Diagonal Windows 21.1.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 6.0
		distanthorizons: Distant Horizons 2.2.1-a
		do_a_barrel_roll: Do a Barrel Roll 3.7.2
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		easyanvils: Easy Anvils 21.1.0
		easyelytratakeoff: Easy Elytra Takeoff 4.4
		easymagic: Easy Magic 21.1.0
		easyshulkerboxes: Easy Shulker Boxes 21.1.0
			iteminteractions: Item Interactions 21.1.0
		eatinganimationid: Eating Animation 1.21+1.9.72
		eldritch_mobs: EldritchMobs 1.16.1
			polymer-blocks: Polymer (Textured Blocks) 0.9.9+1.21
			polymer-core: Polymer (Core) 0.9.9+1.21
				polymer-networking: Polymer (Networking) 0.9.9+1.21
					polymer-common: Polymer (Common) 0.9.9+1.21
						packet_tweaker: Packet Tweaker 0.5.5+1.21
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.9+1.21
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		enhancedvisuals: EnhancedVisuals 1.8.12
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.5
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.0
		euphoria_patcher: Euphoria Patcher 1.4.1-r5.3-fabric
			io_sigpipe_jbsdiff: jbsdiff 1.0
		fabric-api: Fabric API 0.105.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc19
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.23+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.8.0+9d22c5fd19
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.28+1daea21519
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.20+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.0+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.5+3fc0e55219
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.3.0+d831205f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabric-language-kotlin: Fabric Language Kotlin 1.12.3+kotlin.2.0.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.3
		fabricloader: Fabric Loader 0.16.7
		fallingleaves: Falling Leaves 1.16.2
		farmersdelight: Farmer's Delight 1.21-2.1.9+refabricated
			mm: Manningham Mills 2.3
			porting_lib_base: Porting Lib Base 3.1.0-beta+fdrf.1+1.21
				porting_lib_accessors: Porting Lib Accessors 3.1.0-beta+fdrf.1+1.21
				porting_lib_asm: Porting Lib ASM 3.1.0-beta+fdrf.1+1.21
				porting_lib_attributes: Porting Lib Attributes 3.1.0-beta+fdrf.1+1.21
				porting_lib_blocks: Porting Lib Blocks 3.1.0-beta+fdrf.1+1.21
				porting_lib_common: Porting Lib Common 3.1.0-beta+fdrf.1+1.21
				porting_lib_entity: Porting Lib Entity 3.1.0-beta+fdrf.1+1.21
				porting_lib_extensions: Porting Lib Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_fluids: Porting Lib Fluids 3.1.0-beta+fdrf.1+1.21
				porting_lib_gui_utils: Porting Lib Gui Utils 3.1.0-beta+fdrf.1+1.21
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 3.1.0-beta+fdrf.1+1.21
				porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_transfer: Porting Lib Transfer 3.1.0-beta+fdrf.1+1.21
			porting_lib_config: Porting Lib Config 3.1.0-beta+fdrf.1+1.21
				porting_lib_core: Porting Lib Core 3.1.0-beta+fdrf.1+1.21
				porting_lib_gametest: Porting Lib GameTest 3.1.0-beta+fdrf.1+1.21
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0-beta+fdrf.1+1.21
				porting_lib_level_events: Porting Lib Level Events 3.1.0-beta+fdrf.1+1.21
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0-beta+fdrf.1+1.21
			porting_lib_loot: Porting Lib Loot 3.1.0-beta+fdrf.1+1.21
				porting_lib_conditions: Porting Lib Conditions 3.1.0-beta+fdrf.1+1.21
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 3.1.0-beta+fdrf.1+1.21
		ferritecore: FerriteCore 7.0.0
		firstperson: FirstPerson 2.4.5
		fishofthieves: Fish of Thieves 4.0.2
		forgeconfigapiport: Forge Config API Port 21.1.1
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		geckolib: GeckoLib 4 4.6.6
		herdspanic: Herds Panic 1.1.1
		highlighter: Highlighter 1.1.11
		horsebuff: HorseBuff 2.1.8
		iceberg: Iceberg 1.2.7
		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		iris: Iris 1.8.0-beta.4+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		itemborders: Item Borders 1.2.5
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 19.21.0.246
		kiwi: Kiwi Library 15.1.1+fabric
		krypton: Krypton 0.2.8
			com_velocitypowered_velocity-native: velocity-native 3.3.0-SNAPSHOT
		laserbridges: Laser Bridges & Doors 1.21.1-2-fabric
		leahs-immersive-thunder: Immersive Thunder 1.21.1+1.2.2
		legendarytooltips: Legendary Tooltips 1.4.11
		lithium: Lithium 0.13.1
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.19.3+mc1.21.1
		modmenu: Mod Menu 11.0.2
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		monolib: MonoLib 1.3.0
		moonlight: Moonlight Lib 1.21-2.14.31
		moremobvariants: More Mob Variants 1.3.1.1
		mousetweaks: Mouse Tweaks 2.26
		mr_dungeons_andtaverns: Dungeons and Taverns 1-v4.4.4
		mr_vanilla_refresh: Vanilla Refresh 1.4.24j
		mru: Mineblock's Repeated Utilities 1.0.2+1.21+fabric
		netherdepthsupgrade: Nether Depths Upgrade fabric-3.1.8-1.21
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		notenoughanimations: NotEnoughAnimations 1.7.6
		nullscape: Nullscape 1.2.7
		owo: oωo 0.12.15+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		particular: Particular 1.1.1+1.21
		physicsmod: Physics Mod 3.0.20
		playeranimator: Player Animator 2.0.0-alpha1+1.21
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		prism: root project 'Prism' 1.0.9
		puzzleslib: Puzzles Lib 21.1.18
		rolling_down_in_the_deep: Rolling Down in the Deep 0.2.1+1.21
		satin: Satin 2.0.0
		scalablelux: ScalableLux 0.1.0+fabric.26c6e72
		shulkerboxtooltip: Shulker Box Tooltip 5.1.1+1.21.1
		skinlayers3d: 3d-Skin-Layers 1.6.7
		smoothscroll: Smooth Scroll 2.1.3
		snowrealmagic: Snow! Real Magic! 11.0.7+fabric
		sodium: Sodium 0.6.0-beta.2+mc1.21.1
		solid_mobs: Solid Mobs 1.7.1
		soul_fire_d: Soul Fire'd 5.0.4
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		sounds: Sounds 2.1.0+1.21+fabric
			architectury: Architectury 13.0.6
			mixinextras: MixinExtras 0.5.0-beta.2
			yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		sparsestructures: SparseStructures 2.2.0
		superbettergrass: SuperBetterGrass 1.5.3+1.21
		t_and_t: Towns and Towers 1.13.2
		tcdcommons: TCD Commons API 3.12.3+fabric-1.21
		tectonic: Tectonic 2.4.1a
		terralith: Terralith 2.5.5
		tia: Tiny Item Animations 1.2.1
		tide: Tide 1.3.3
		tinyskeletons: Tiny Skeletons 21.1.0
		tool_trims: Tool Trims 2.2.1
		trinkets: Trinkets 3.10.0
		universalbonemeal: Universal Bone Meal 21.1.0
		visuality: Visuality 0.7.7+1.21
		waystones: Waystones 21.1.4
		wover: WorldWeaver 21.0.13
			wover-biome: WorldWeaver - Biome API 21.0.13
			wover-block: WorldWeaver - Block and Item API 21.0.13
			wover-common: WorldWeaver - Common API 21.0.13
			wover-core: WorldWeaver - Core API 21.0.13
			wover-datagen: WorldWeaver - Datagen API 21.0.13
			wover-events: WorldWeaver - Events API 21.0.13
			wover-feature: WorldWeaver - Feature API 21.0.13
			wover-generator: WorldWeaver - World Generator API 21.0.13
			wover-item: WorldWeaver - Item API 21.0.13
			wover-math: WorldWeaver - Math API 21.0.13
			wover-preset: WorldWeaver - World Preset API 21.0.13
			wover-recipe: WorldWeaver - Recipe API 21.0.13
			wover-structure: WorldWeaver - Structure API 21.0.13
			wover-surface: WorldWeaver - Surface API 21.0.13
			wover-tag: WorldWeaver - Tag API 21.0.13
			wover-ui: WorldWeaver - UI API 21.0.13
		wunderlib: WunderLib 21.0.8
	Loaded Shaderpack: ComplementaryUnbound_r5.3 + EuphoriaPatches_1.4.1
		Profile: Custom (+55 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Sabert25'/59, l='ServerLevel[Neue Welt]', x=96.15, y=140.12, z=3.23]]
	Active Data Packs: vanilla, fabric, advancednetherite, amendments, amplified_nether (incompatible), animal_feeding_trough, balm-fabric (incompatible), bclib, bettercombat, betterend, betternether, betternetherdelight, bosses_of_mass_destruction, collective, comforts (incompatible), connectiblechains, danger_close (incompatible), diagonalblocks (incompatible), easyanvils (incompatible), easymagic (incompatible), easyshulkerboxes (incompatible), eldritch_mobs, fabric-convention-tags-v2, farmersdelight, fishofthieves, laserbridges, moonlight, moremobvariants, mr_dungeons_andtaverns, mr_vanilla_refresh, netherdepthsupgrade, nullscape, porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, server_translations_api, snowrealmagic (incompatible), soul_fire_d (incompatible), sounds (incompatible), t_and_t, terralith, tide (incompatible), tinyskeletons (incompatible), tool_trims, trinkets, universalbonemeal (incompatible), waystones (incompatible), wover-generator, wover-preset, wover-surface, wover-tag, towns_and_towers:resources/t_and_t_waystones_patch, moonlight:mods_dynamic_assets, soul_fire_d:campfire_tags, soul_fire_d:fire_source_tags, tectonic:tectonic
	Available Data Packs: advancednetherite, amendments, amplified_nether (incompatible), animal_feeding_trough, balm-fabric (incompatible), bclib, bettercombat, betterend, betterend:nourish_extensions, betterend:patchouli_extensions, betternether, betternether:vanilla-hammers_extensions, betternether:vanillaexcavators_extensions, betternetherdelight, bosses_of_mass_destruction, bundle, collective, comforts (incompatible), connectiblechains, danger_close (incompatible), diagonalblocks (incompatible), easyanvils (incompatible), easymagic (incompatible), easyshulkerboxes (incompatible), eldritch_mobs, fabric, fabric-convention-tags-v2, farmersdelight, fishofthieves, fishofthieves:simple_spawning_condition_pack, laserbridges, moonlight, moonlight:mods_dynamic_assets, moremobvariants, mr_dungeons_andtaverns, mr_vanilla_refresh, netherdepthsupgrade, nullscape, porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, server_translations_api, snowrealmagic (incompatible), soul_fire_d (incompatible), soul_fire_d:campfire_tags, soul_fire_d:fire_source_tags, sounds (incompatible), t_and_t, tectonic:tectonic, terralith, tide (incompatible), tinyskeletons (incompatible), tool_trims, towns_and_towers:resources/t_and_t_waystones_patch, trade_rebalance, trinkets, universalbonemeal (incompatible), vanilla, waystones (incompatible), wover-generator, wover-preset, wover-surface, wover-tag
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	World Seed: -5735402573727039243
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.7-1.21.1

**Comment by MindStudioOfficial** [comment]
Got a similar crash when teleporting very far on my map

[1.21.1]

```
[13:51:54] [Server thread/WARN]: MindStudio moved too quickly! 2890.549924705154,148.5,1931.2776383219352

[13:51:54] [Server thread/WARN]: MindStudio moved too quickly! 2890.549924705154,148.5,1931.2776383219352

[13:51:54] [Server thread/ERROR]: Encountered an unexpected exception

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 2049

	at knot/it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$1.forEach(Int2ObjectLinkedOpenHashMap.java:1718) ~[fastutil-8.5.12.jar:?]

	at knot/com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:110) ~[guava-32.1.2-jre.jar:?]

	at knot/fabric.com.cursee.danger_close.DangerCloseFabric.lambda$onInitialize$1(DangerCloseFabric.java:26) ~[danger_close-merged-1.21-3.1.1.jar:?]

	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(Unknown Source) ~[?:?]

	at knot/fabric.com.cursee.danger_close.DangerCloseFabric.lambda$onInitialize$2(DangerCloseFabric.java:22) ~[danger_close-merged-1.21-3.1.1.jar:?]

	at knot/net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:34) ~[fabric-lifecycle-events-v1-2.5.0+01d9a51c19-8ff401bae2cee6b0.jar:?]

	at knot/net.minecraft.server.MinecraftServer.handler$bia000$fabric-lifecycle-events-v1$onStartTick(MinecraftServer.java:5158) ~[server-intermediary.jar:?]

	at knot/net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]

	at knot/net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]

	at knot/net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]

	at java.base/java.lang.Thread.run(Unknown Source) [?:?]

[13:51:54] [Server thread/ERROR]: This crash report has been saved to: /data/crash-reports/crash-2024-12-04_13.51.54-server.txt

```
